name: Build protobuf

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Reason'     
        required: false
        default: 'Update package'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'false'

      - name: Prerequisites
        run: |
          sudo apt install \
          make \
          autogen \
          autoconf \
          -y

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25b
          add-to-path: false
      - run: bash build.sh
        env:
          ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: protobuf-aarch64
          path: google/protobuf/arm64_build
